//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CH_USER()
        {
            this.APPLIEDCOUPONS = new HashSet<APPLIEDCOUPON>();
            this.transactions = new HashSet<transaction>();
            this.USERCOUPONS = new HashSet<USERCOUPON>();
            this.WALLETs = new HashSet<WALLET>();
        }
    
        public int USER_ID { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USER_EMAILID { get; set; }
        public string USER_MOBILE { get; set; }
        public string USER_USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_DEVICEID { get; set; }
        public Nullable<int> USER_REGISTERTYPE { get; set; }
        public Nullable<int> USER_STATUS { get; set; }
        public Nullable<int> USER_CREATEDBY { get; set; }
        public Nullable<System.DateTime> USER_CREATEDATE { get; set; }
        public Nullable<int> USER_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> USER_MODIFIEDDATE { get; set; }
        public Nullable<bool> USER_COUPONAPPLIED { get; set; }
        public Nullable<int> USER_REFEREDBY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLIEDCOUPON> APPLIEDCOUPONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERCOUPON> USERCOUPONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WALLET> WALLETs { get; set; }
        public virtual USER_REGISTERTYPE USER_REGISTERTYPE1 { get; set; }
        public virtual USER_STATUS USER_STATUS1 { get; set; }
    }
}
