//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_USER
    {
        public int USER_ID { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USER_EMAILID { get; set; }
        public string USER_MOBILE { get; set; }
        public string USER_USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_DEVICEID { get; set; }
        public Nullable<int> USER_REGISTERTYPE { get; set; }
        public Nullable<int> USER_STAUS { get; set; }
        public Nullable<int> USER_CREATEDBY { get; set; }
        public Nullable<System.DateTime> USER_CREATEDATE { get; set; }
        public Nullable<int> USER_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> USER_MODIFIEDDATE { get; set; }
    
        public virtual USER_REGISTERTYPE USER_REGISTERTYPE1 { get; set; }
        public virtual USER_STATUS USER_STATUS { get; set; }
    }
}
