//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHALOEntities : DbContext
    {
        public CHALOEntities()
            : base("name=CHALOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLIEDCOUPON> APPLIEDCOUPONS { get; set; }
        public virtual DbSet<CITy> CITIES { get; set; }
        public virtual DbSet<COUPONENTIYPURPOSE> COUPONENTIYPURPOSEs { get; set; }
        public virtual DbSet<COUPON> COUPONS { get; set; }
        public virtual DbSet<COUPONTYPE> COUPONTYPEs { get; set; }
        public virtual DbSet<DRIVERTRIPSENTITY> DRIVERTRIPSENTITies { get; set; }
        public virtual DbSet<DRIVERTRIPSREWRITE> DRIVERTRIPSREWRITEs { get; set; }
        public virtual DbSet<LOCATIONENTITY> LOCATIONENTITies { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<PASSENGERSENTITY> PASSENGERSENTITies { get; set; }
        public virtual DbSet<PAYMENTTRIPSTATU> PAYMENTTRIPSTATUS { get; set; }
        public virtual DbSet<SUPPORT> SUPPORTs { get; set; }
        public virtual DbSet<TRANSACTIONMODE> TRANSACTIONMODEs { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<TRANSACTIONSTATU> TRANSACTIONSTATUS { get; set; }
        public virtual DbSet<TRIPHISTORYENTITY> TRIPHISTORYENTITies { get; set; }
        public virtual DbSet<TripUsersEntity> TripUsersEntities { get; set; }
        public virtual DbSet<USERCOUPON> USERCOUPONS { get; set; }
        public virtual DbSet<WALLET> WALLETs { get; set; }
        public virtual DbSet<WALLETADDTYPE> WALLETADDTYPES { get; set; }
        public virtual DbSet<WALLETTRANSACTION> WALLETTRANSACTIONS { get; set; }
        public virtual DbSet<WALLETTRANSACTIONSSTATU> WALLETTRANSACTIONSSTATUS { get; set; }
        public virtual DbSet<CH_USER> CH_USER { get; set; }
        public virtual DbSet<CITIES1> CITIES1 { get; set; }
        public virtual DbSet<DRIVER> DRIVERS { get; set; }
        public virtual DbSet<LOCATIONS1> LOCATIONS1 { get; set; }
        public virtual DbSet<MASTERSTATU> MASTERSTATUS { get; set; }
        public virtual DbSet<NOOFSEAT> NOOFSEATS { get; set; }
        public virtual DbSet<PAYMENTHISTORY> PAYMENTHISTORies { get; set; }
        public virtual DbSet<PAYMENTTYPE> PAYMENTTYPEs { get; set; }
        public virtual DbSet<ROUTE> ROUTES { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<temptrip> temptrips { get; set; }
        public virtual DbSet<TRIPLOCATION> TRIPLOCATIONS { get; set; }
        public virtual DbSet<TRIP> TRIPS { get; set; }
        public virtual DbSet<TRIPSTATU> TRIPSTATUS { get; set; }
        public virtual DbSet<TRIPTEMP> TRIPTEMPs { get; set; }
        public virtual DbSet<USER_REGISTERTYPE> USER_REGISTERTYPE { get; set; }
        public virtual DbSet<USER_STATUS> USER_STATUS { get; set; }
        public virtual DbSet<USERTRIP> USERTRIPS { get; set; }
        public virtual DbSet<VEHICLEDRIVER> VEHICLEDRIVERS { get; set; }
        public virtual DbSet<VEHICLE> VEHICLES { get; set; }
        public virtual DbSet<VEHICLETYPE> VEHICLETYPEs { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
    
        public virtual int USP_GETVEHICLEBYTRIP(string dROPLOCATION, string pICKUPLOCATION, Nullable<int> tRIP_ID)
        {
            var dROPLOCATIONParameter = dROPLOCATION != null ?
                new ObjectParameter("DROPLOCATION", dROPLOCATION) :
                new ObjectParameter("DROPLOCATION", typeof(string));
    
            var pICKUPLOCATIONParameter = pICKUPLOCATION != null ?
                new ObjectParameter("PICKUPLOCATION", pICKUPLOCATION) :
                new ObjectParameter("PICKUPLOCATION", typeof(string));
    
            var tRIP_IDParameter = tRIP_ID.HasValue ?
                new ObjectParameter("TRIP_ID", tRIP_ID) :
                new ObjectParameter("TRIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GETVEHICLEBYTRIP", dROPLOCATIONParameter, pICKUPLOCATIONParameter, tRIP_IDParameter);
        }
    
        public virtual int USP_SEARCHVEHICLES(string dROPLOCATION, string pICKUPLOCATION)
        {
            var dROPLOCATIONParameter = dROPLOCATION != null ?
                new ObjectParameter("DROPLOCATION", dROPLOCATION) :
                new ObjectParameter("DROPLOCATION", typeof(string));
    
            var pICKUPLOCATIONParameter = pICKUPLOCATION != null ?
                new ObjectParameter("PICKUPLOCATION", pICKUPLOCATION) :
                new ObjectParameter("PICKUPLOCATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SEARCHVEHICLES", dROPLOCATIONParameter, pICKUPLOCATIONParameter);
        }
    
        public virtual ObjectResult<USP_BOOKCAB_Result> USP_BOOKCAB(Nullable<int> uSER_ID, Nullable<int> uSERTRIP_ID, Nullable<int> uSERTRIP_TRIPID, Nullable<int> uSERTRIP_PICKUPLOC, Nullable<int> uSERTRIP_DROPLOC, string uSERTRIP_VIA, Nullable<int> uSERTRIP_ESTIMATEDDURATION, Nullable<int> uSERTRIP_ACTUALDURATION, Nullable<int> uSERTRIP_DISTANCE, Nullable<decimal> uSERTRIP_ACTUALAMOUNT, Nullable<decimal> uSERTRIP_DISCOUNT, Nullable<decimal> uSERTRIP_TOTALAMOUNT, Nullable<int> uSERTRIP_STATUS, Nullable<int> uSERTRIP_APPLIEDCOUPON, Nullable<int> uSERTRIP_CREATEDBY, Nullable<System.DateTime> uSERTRIP_CREATEDDATE, Nullable<int> uSERTRIP_MODIFIEDBY, Nullable<System.DateTime> uSERTRIP_MODIFIEDDATE, Nullable<int> tRANS_STATUS, Nullable<int> pAYMENTTYPE_ID, string aPPLIEDCOUPONNAME, Nullable<bool> iSONETIME, Nullable<System.DateTime> usertrip_pickupavergetime, Nullable<System.DateTime> usertrip_pickupactualtime, Nullable<System.DateTime> usertrip_dropaveragetime, Nullable<System.DateTime> usertrip_dropactualtime, string oPERATION, Nullable<int> wALLET_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var uSERTRIP_IDParameter = uSERTRIP_ID.HasValue ?
                new ObjectParameter("USERTRIP_ID", uSERTRIP_ID) :
                new ObjectParameter("USERTRIP_ID", typeof(int));
    
            var uSERTRIP_TRIPIDParameter = uSERTRIP_TRIPID.HasValue ?
                new ObjectParameter("USERTRIP_TRIPID", uSERTRIP_TRIPID) :
                new ObjectParameter("USERTRIP_TRIPID", typeof(int));
    
            var uSERTRIP_PICKUPLOCParameter = uSERTRIP_PICKUPLOC.HasValue ?
                new ObjectParameter("USERTRIP_PICKUPLOC", uSERTRIP_PICKUPLOC) :
                new ObjectParameter("USERTRIP_PICKUPLOC", typeof(int));
    
            var uSERTRIP_DROPLOCParameter = uSERTRIP_DROPLOC.HasValue ?
                new ObjectParameter("USERTRIP_DROPLOC", uSERTRIP_DROPLOC) :
                new ObjectParameter("USERTRIP_DROPLOC", typeof(int));
    
            var uSERTRIP_VIAParameter = uSERTRIP_VIA != null ?
                new ObjectParameter("USERTRIP_VIA", uSERTRIP_VIA) :
                new ObjectParameter("USERTRIP_VIA", typeof(string));
    
            var uSERTRIP_ESTIMATEDDURATIONParameter = uSERTRIP_ESTIMATEDDURATION.HasValue ?
                new ObjectParameter("USERTRIP_ESTIMATEDDURATION", uSERTRIP_ESTIMATEDDURATION) :
                new ObjectParameter("USERTRIP_ESTIMATEDDURATION", typeof(int));
    
            var uSERTRIP_ACTUALDURATIONParameter = uSERTRIP_ACTUALDURATION.HasValue ?
                new ObjectParameter("USERTRIP_ACTUALDURATION", uSERTRIP_ACTUALDURATION) :
                new ObjectParameter("USERTRIP_ACTUALDURATION", typeof(int));
    
            var uSERTRIP_DISTANCEParameter = uSERTRIP_DISTANCE.HasValue ?
                new ObjectParameter("USERTRIP_DISTANCE", uSERTRIP_DISTANCE) :
                new ObjectParameter("USERTRIP_DISTANCE", typeof(int));
    
            var uSERTRIP_ACTUALAMOUNTParameter = uSERTRIP_ACTUALAMOUNT.HasValue ?
                new ObjectParameter("USERTRIP_ACTUALAMOUNT", uSERTRIP_ACTUALAMOUNT) :
                new ObjectParameter("USERTRIP_ACTUALAMOUNT", typeof(decimal));
    
            var uSERTRIP_DISCOUNTParameter = uSERTRIP_DISCOUNT.HasValue ?
                new ObjectParameter("USERTRIP_DISCOUNT", uSERTRIP_DISCOUNT) :
                new ObjectParameter("USERTRIP_DISCOUNT", typeof(decimal));
    
            var uSERTRIP_TOTALAMOUNTParameter = uSERTRIP_TOTALAMOUNT.HasValue ?
                new ObjectParameter("USERTRIP_TOTALAMOUNT", uSERTRIP_TOTALAMOUNT) :
                new ObjectParameter("USERTRIP_TOTALAMOUNT", typeof(decimal));
    
            var uSERTRIP_STATUSParameter = uSERTRIP_STATUS.HasValue ?
                new ObjectParameter("USERTRIP_STATUS", uSERTRIP_STATUS) :
                new ObjectParameter("USERTRIP_STATUS", typeof(int));
    
            var uSERTRIP_APPLIEDCOUPONParameter = uSERTRIP_APPLIEDCOUPON.HasValue ?
                new ObjectParameter("USERTRIP_APPLIEDCOUPON", uSERTRIP_APPLIEDCOUPON) :
                new ObjectParameter("USERTRIP_APPLIEDCOUPON", typeof(int));
    
            var uSERTRIP_CREATEDBYParameter = uSERTRIP_CREATEDBY.HasValue ?
                new ObjectParameter("USERTRIP_CREATEDBY", uSERTRIP_CREATEDBY) :
                new ObjectParameter("USERTRIP_CREATEDBY", typeof(int));
    
            var uSERTRIP_CREATEDDATEParameter = uSERTRIP_CREATEDDATE.HasValue ?
                new ObjectParameter("USERTRIP_CREATEDDATE", uSERTRIP_CREATEDDATE) :
                new ObjectParameter("USERTRIP_CREATEDDATE", typeof(System.DateTime));
    
            var uSERTRIP_MODIFIEDBYParameter = uSERTRIP_MODIFIEDBY.HasValue ?
                new ObjectParameter("USERTRIP_MODIFIEDBY", uSERTRIP_MODIFIEDBY) :
                new ObjectParameter("USERTRIP_MODIFIEDBY", typeof(int));
    
            var uSERTRIP_MODIFIEDDATEParameter = uSERTRIP_MODIFIEDDATE.HasValue ?
                new ObjectParameter("USERTRIP_MODIFIEDDATE", uSERTRIP_MODIFIEDDATE) :
                new ObjectParameter("USERTRIP_MODIFIEDDATE", typeof(System.DateTime));
    
            var tRANS_STATUSParameter = tRANS_STATUS.HasValue ?
                new ObjectParameter("TRANS_STATUS", tRANS_STATUS) :
                new ObjectParameter("TRANS_STATUS", typeof(int));
    
            var pAYMENTTYPE_IDParameter = pAYMENTTYPE_ID.HasValue ?
                new ObjectParameter("PAYMENTTYPE_ID", pAYMENTTYPE_ID) :
                new ObjectParameter("PAYMENTTYPE_ID", typeof(int));
    
            var aPPLIEDCOUPONNAMEParameter = aPPLIEDCOUPONNAME != null ?
                new ObjectParameter("APPLIEDCOUPONNAME", aPPLIEDCOUPONNAME) :
                new ObjectParameter("APPLIEDCOUPONNAME", typeof(string));
    
            var iSONETIMEParameter = iSONETIME.HasValue ?
                new ObjectParameter("ISONETIME", iSONETIME) :
                new ObjectParameter("ISONETIME", typeof(bool));
    
            var usertrip_pickupavergetimeParameter = usertrip_pickupavergetime.HasValue ?
                new ObjectParameter("usertrip_pickupavergetime", usertrip_pickupavergetime) :
                new ObjectParameter("usertrip_pickupavergetime", typeof(System.DateTime));
    
            var usertrip_pickupactualtimeParameter = usertrip_pickupactualtime.HasValue ?
                new ObjectParameter("usertrip_pickupactualtime", usertrip_pickupactualtime) :
                new ObjectParameter("usertrip_pickupactualtime", typeof(System.DateTime));
    
            var usertrip_dropaveragetimeParameter = usertrip_dropaveragetime.HasValue ?
                new ObjectParameter("usertrip_dropaveragetime", usertrip_dropaveragetime) :
                new ObjectParameter("usertrip_dropaveragetime", typeof(System.DateTime));
    
            var usertrip_dropactualtimeParameter = usertrip_dropactualtime.HasValue ?
                new ObjectParameter("usertrip_dropactualtime", usertrip_dropactualtime) :
                new ObjectParameter("usertrip_dropactualtime", typeof(System.DateTime));
    
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            var wALLET_IDParameter = wALLET_ID.HasValue ?
                new ObjectParameter("WALLET_ID", wALLET_ID) :
                new ObjectParameter("WALLET_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BOOKCAB_Result>("USP_BOOKCAB", uSER_IDParameter, uSERTRIP_IDParameter, uSERTRIP_TRIPIDParameter, uSERTRIP_PICKUPLOCParameter, uSERTRIP_DROPLOCParameter, uSERTRIP_VIAParameter, uSERTRIP_ESTIMATEDDURATIONParameter, uSERTRIP_ACTUALDURATIONParameter, uSERTRIP_DISTANCEParameter, uSERTRIP_ACTUALAMOUNTParameter, uSERTRIP_DISCOUNTParameter, uSERTRIP_TOTALAMOUNTParameter, uSERTRIP_STATUSParameter, uSERTRIP_APPLIEDCOUPONParameter, uSERTRIP_CREATEDBYParameter, uSERTRIP_CREATEDDATEParameter, uSERTRIP_MODIFIEDBYParameter, uSERTRIP_MODIFIEDDATEParameter, tRANS_STATUSParameter, pAYMENTTYPE_IDParameter, aPPLIEDCOUPONNAMEParameter, iSONETIMEParameter, usertrip_pickupavergetimeParameter, usertrip_pickupactualtimeParameter, usertrip_dropaveragetimeParameter, usertrip_dropactualtimeParameter, oPERATIONParameter, wALLET_IDParameter);
        }
    
        public virtual ObjectResult<USP_GETLOCS_Result> USP_GETLOCS(Nullable<int> lOCATION_ID, string oPERATION, string fROMLOCATION, string cITY_NAME)
        {
            var lOCATION_IDParameter = lOCATION_ID.HasValue ?
                new ObjectParameter("LOCATION_ID", lOCATION_ID) :
                new ObjectParameter("LOCATION_ID", typeof(int));
    
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            var fROMLOCATIONParameter = fROMLOCATION != null ?
                new ObjectParameter("FROMLOCATION", fROMLOCATION) :
                new ObjectParameter("FROMLOCATION", typeof(string));
    
            var cITY_NAMEParameter = cITY_NAME != null ?
                new ObjectParameter("CITY_NAME", cITY_NAME) :
                new ObjectParameter("CITY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GETLOCS_Result>("USP_GETLOCS", lOCATION_IDParameter, oPERATIONParameter, fROMLOCATIONParameter, cITY_NAMEParameter);
        }
    
        public virtual ObjectResult<USP_CHECKFORCOUPON_Result> USP_CHECKFORCOUPON(Nullable<int> uSER_ID, string cOUPONCODE, string oPERATION)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var cOUPONCODEParameter = cOUPONCODE != null ?
                new ObjectParameter("COUPONCODE", cOUPONCODE) :
                new ObjectParameter("COUPONCODE", typeof(string));
    
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CHECKFORCOUPON_Result>("USP_CHECKFORCOUPON", uSER_IDParameter, cOUPONCODEParameter, oPERATIONParameter);
        }
    
        public virtual ObjectResult<CHECKWALLETAMOUNT_Result> CHECKWALLETAMOUNT(Nullable<int> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHECKWALLETAMOUNT_Result>("CHECKWALLETAMOUNT", uSER_IDParameter);
        }
    
        public virtual ObjectResult<noofseatsavailability_Result> noofseatsavailability(Nullable<int> tRIP_ID)
        {
            var tRIP_IDParameter = tRIP_ID.HasValue ?
                new ObjectParameter("TRIP_ID", tRIP_ID) :
                new ObjectParameter("TRIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<noofseatsavailability_Result>("noofseatsavailability", tRIP_IDParameter);
        }
    
        public virtual ObjectResult<USP_TRIPHISTORY_Result> USP_TRIPHISTORY(Nullable<int> tRIP_ID, Nullable<int> uSER_ID, string oPERATION)
        {
            var tRIP_IDParameter = tRIP_ID.HasValue ?
                new ObjectParameter("TRIP_ID", tRIP_ID) :
                new ObjectParameter("TRIP_ID", typeof(int));
    
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TRIPHISTORY_Result>("USP_TRIPHISTORY", tRIP_IDParameter, uSER_IDParameter, oPERATIONParameter);
        }
    
        public virtual ObjectResult<GetDriverTripDetails_Result> GetDriverTripDetails(Nullable<int> driver_Id)
        {
            var driver_IdParameter = driver_Id.HasValue ?
                new ObjectParameter("Driver_Id", driver_Id) :
                new ObjectParameter("Driver_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDriverTripDetails_Result>("GetDriverTripDetails", driver_IdParameter);
        }
    
        public virtual int vendors_data(string vENDOR_ORGANIZATIONNAME, string vENDOR_ORGANIZATIONMOBILE, string vENDOR_ORGANIZATIONLANDLINE, string vENDOR_OWNFIRSTNAME, string vENDOR_OWNLASTNAME, string vENDOR_CONFIRSTNAME, string vENDOR_CONLASTNAME, string vENDOR_EMAILID, string vENDOR_ADDRESS, string vENDOR_OWNMOBILE, string vENDOR_CONMOBILE, string vENDOR_OWNLANDLINE, string vENDOR_CONLANDLINE, string vENDOR_USERNAME, string vENDOR_PASSWORD, string vENDOR_STATUS, string vENDOR_CREATEDBY, string vENDOR_MODIFIEDBY, string vENDOR_MODIFIEDDATE, string operation)
        {
            var vENDOR_ORGANIZATIONNAMEParameter = vENDOR_ORGANIZATIONNAME != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONNAME", vENDOR_ORGANIZATIONNAME) :
                new ObjectParameter("VENDOR_ORGANIZATIONNAME", typeof(string));
    
            var vENDOR_ORGANIZATIONMOBILEParameter = vENDOR_ORGANIZATIONMOBILE != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONMOBILE", vENDOR_ORGANIZATIONMOBILE) :
                new ObjectParameter("VENDOR_ORGANIZATIONMOBILE", typeof(string));
    
            var vENDOR_ORGANIZATIONLANDLINEParameter = vENDOR_ORGANIZATIONLANDLINE != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONLANDLINE", vENDOR_ORGANIZATIONLANDLINE) :
                new ObjectParameter("VENDOR_ORGANIZATIONLANDLINE", typeof(string));
    
            var vENDOR_OWNFIRSTNAMEParameter = vENDOR_OWNFIRSTNAME != null ?
                new ObjectParameter("VENDOR_OWNFIRSTNAME", vENDOR_OWNFIRSTNAME) :
                new ObjectParameter("VENDOR_OWNFIRSTNAME", typeof(string));
    
            var vENDOR_OWNLASTNAMEParameter = vENDOR_OWNLASTNAME != null ?
                new ObjectParameter("VENDOR_OWNLASTNAME", vENDOR_OWNLASTNAME) :
                new ObjectParameter("VENDOR_OWNLASTNAME", typeof(string));
    
            var vENDOR_CONFIRSTNAMEParameter = vENDOR_CONFIRSTNAME != null ?
                new ObjectParameter("VENDOR_CONFIRSTNAME", vENDOR_CONFIRSTNAME) :
                new ObjectParameter("VENDOR_CONFIRSTNAME", typeof(string));
    
            var vENDOR_CONLASTNAMEParameter = vENDOR_CONLASTNAME != null ?
                new ObjectParameter("VENDOR_CONLASTNAME", vENDOR_CONLASTNAME) :
                new ObjectParameter("VENDOR_CONLASTNAME", typeof(string));
    
            var vENDOR_EMAILIDParameter = vENDOR_EMAILID != null ?
                new ObjectParameter("VENDOR_EMAILID", vENDOR_EMAILID) :
                new ObjectParameter("VENDOR_EMAILID", typeof(string));
    
            var vENDOR_ADDRESSParameter = vENDOR_ADDRESS != null ?
                new ObjectParameter("VENDOR_ADDRESS", vENDOR_ADDRESS) :
                new ObjectParameter("VENDOR_ADDRESS", typeof(string));
    
            var vENDOR_OWNMOBILEParameter = vENDOR_OWNMOBILE != null ?
                new ObjectParameter("VENDOR_OWNMOBILE", vENDOR_OWNMOBILE) :
                new ObjectParameter("VENDOR_OWNMOBILE", typeof(string));
    
            var vENDOR_CONMOBILEParameter = vENDOR_CONMOBILE != null ?
                new ObjectParameter("VENDOR_CONMOBILE", vENDOR_CONMOBILE) :
                new ObjectParameter("VENDOR_CONMOBILE", typeof(string));
    
            var vENDOR_OWNLANDLINEParameter = vENDOR_OWNLANDLINE != null ?
                new ObjectParameter("VENDOR_OWNLANDLINE", vENDOR_OWNLANDLINE) :
                new ObjectParameter("VENDOR_OWNLANDLINE", typeof(string));
    
            var vENDOR_CONLANDLINEParameter = vENDOR_CONLANDLINE != null ?
                new ObjectParameter("VENDOR_CONLANDLINE", vENDOR_CONLANDLINE) :
                new ObjectParameter("VENDOR_CONLANDLINE", typeof(string));
    
            var vENDOR_USERNAMEParameter = vENDOR_USERNAME != null ?
                new ObjectParameter("VENDOR_USERNAME", vENDOR_USERNAME) :
                new ObjectParameter("VENDOR_USERNAME", typeof(string));
    
            var vENDOR_PASSWORDParameter = vENDOR_PASSWORD != null ?
                new ObjectParameter("VENDOR_PASSWORD", vENDOR_PASSWORD) :
                new ObjectParameter("VENDOR_PASSWORD", typeof(string));
    
            var vENDOR_STATUSParameter = vENDOR_STATUS != null ?
                new ObjectParameter("VENDOR_STATUS", vENDOR_STATUS) :
                new ObjectParameter("VENDOR_STATUS", typeof(string));
    
            var vENDOR_CREATEDBYParameter = vENDOR_CREATEDBY != null ?
                new ObjectParameter("VENDOR_CREATEDBY", vENDOR_CREATEDBY) :
                new ObjectParameter("VENDOR_CREATEDBY", typeof(string));
    
            var vENDOR_MODIFIEDBYParameter = vENDOR_MODIFIEDBY != null ?
                new ObjectParameter("VENDOR_MODIFIEDBY", vENDOR_MODIFIEDBY) :
                new ObjectParameter("VENDOR_MODIFIEDBY", typeof(string));
    
            var vENDOR_MODIFIEDDATEParameter = vENDOR_MODIFIEDDATE != null ?
                new ObjectParameter("VENDOR_MODIFIEDDATE", vENDOR_MODIFIEDDATE) :
                new ObjectParameter("VENDOR_MODIFIEDDATE", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vendors_data", vENDOR_ORGANIZATIONNAMEParameter, vENDOR_ORGANIZATIONMOBILEParameter, vENDOR_ORGANIZATIONLANDLINEParameter, vENDOR_OWNFIRSTNAMEParameter, vENDOR_OWNLASTNAMEParameter, vENDOR_CONFIRSTNAMEParameter, vENDOR_CONLASTNAMEParameter, vENDOR_EMAILIDParameter, vENDOR_ADDRESSParameter, vENDOR_OWNMOBILEParameter, vENDOR_CONMOBILEParameter, vENDOR_OWNLANDLINEParameter, vENDOR_CONLANDLINEParameter, vENDOR_USERNAMEParameter, vENDOR_PASSWORDParameter, vENDOR_STATUSParameter, vENDOR_CREATEDBYParameter, vENDOR_MODIFIEDBYParameter, vENDOR_MODIFIEDDATEParameter, operationParameter);
        }
    
        public virtual int vendors_details(Nullable<int> vENDOR_ID, string vENDOR_ORGANIZATIONNAME, string vENDOR_ORGANIZATIONMOBILE, string vENDOR_ORGANIZATIONLANDLINE, string vENDOR_OWNFIRSTNAME, string vENDOR_OWNLASTNAME, string vENDOR_CONFIRSTNAME, string vENDOR_CONLASTNAME, string vENDOR_EMAILID, string vENDOR_ADDRESS, string vENDOR_OWNMOBILE, string vENDOR_CONMOBILE, string vENDOR_OWNLANDLINE, string vENDOR_CONLANDLINE, string vENDOR_USERNAME, string vENDOR_PASSWORD, Nullable<int> vENDOR_STATUS, Nullable<int> vENDOR_CREATEDBY, Nullable<System.DateTime> vENDOR_CREATEDDATE, Nullable<int> vENDOR_MODIFIEDBY, Nullable<System.DateTime> vENDOR_MODIFIEDDATE, string operation)
        {
            var vENDOR_IDParameter = vENDOR_ID.HasValue ?
                new ObjectParameter("VENDOR_ID", vENDOR_ID) :
                new ObjectParameter("VENDOR_ID", typeof(int));
    
            var vENDOR_ORGANIZATIONNAMEParameter = vENDOR_ORGANIZATIONNAME != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONNAME", vENDOR_ORGANIZATIONNAME) :
                new ObjectParameter("VENDOR_ORGANIZATIONNAME", typeof(string));
    
            var vENDOR_ORGANIZATIONMOBILEParameter = vENDOR_ORGANIZATIONMOBILE != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONMOBILE", vENDOR_ORGANIZATIONMOBILE) :
                new ObjectParameter("VENDOR_ORGANIZATIONMOBILE", typeof(string));
    
            var vENDOR_ORGANIZATIONLANDLINEParameter = vENDOR_ORGANIZATIONLANDLINE != null ?
                new ObjectParameter("VENDOR_ORGANIZATIONLANDLINE", vENDOR_ORGANIZATIONLANDLINE) :
                new ObjectParameter("VENDOR_ORGANIZATIONLANDLINE", typeof(string));
    
            var vENDOR_OWNFIRSTNAMEParameter = vENDOR_OWNFIRSTNAME != null ?
                new ObjectParameter("VENDOR_OWNFIRSTNAME", vENDOR_OWNFIRSTNAME) :
                new ObjectParameter("VENDOR_OWNFIRSTNAME", typeof(string));
    
            var vENDOR_OWNLASTNAMEParameter = vENDOR_OWNLASTNAME != null ?
                new ObjectParameter("VENDOR_OWNLASTNAME", vENDOR_OWNLASTNAME) :
                new ObjectParameter("VENDOR_OWNLASTNAME", typeof(string));
    
            var vENDOR_CONFIRSTNAMEParameter = vENDOR_CONFIRSTNAME != null ?
                new ObjectParameter("VENDOR_CONFIRSTNAME", vENDOR_CONFIRSTNAME) :
                new ObjectParameter("VENDOR_CONFIRSTNAME", typeof(string));
    
            var vENDOR_CONLASTNAMEParameter = vENDOR_CONLASTNAME != null ?
                new ObjectParameter("VENDOR_CONLASTNAME", vENDOR_CONLASTNAME) :
                new ObjectParameter("VENDOR_CONLASTNAME", typeof(string));
    
            var vENDOR_EMAILIDParameter = vENDOR_EMAILID != null ?
                new ObjectParameter("VENDOR_EMAILID", vENDOR_EMAILID) :
                new ObjectParameter("VENDOR_EMAILID", typeof(string));
    
            var vENDOR_ADDRESSParameter = vENDOR_ADDRESS != null ?
                new ObjectParameter("VENDOR_ADDRESS", vENDOR_ADDRESS) :
                new ObjectParameter("VENDOR_ADDRESS", typeof(string));
    
            var vENDOR_OWNMOBILEParameter = vENDOR_OWNMOBILE != null ?
                new ObjectParameter("VENDOR_OWNMOBILE", vENDOR_OWNMOBILE) :
                new ObjectParameter("VENDOR_OWNMOBILE", typeof(string));
    
            var vENDOR_CONMOBILEParameter = vENDOR_CONMOBILE != null ?
                new ObjectParameter("VENDOR_CONMOBILE", vENDOR_CONMOBILE) :
                new ObjectParameter("VENDOR_CONMOBILE", typeof(string));
    
            var vENDOR_OWNLANDLINEParameter = vENDOR_OWNLANDLINE != null ?
                new ObjectParameter("VENDOR_OWNLANDLINE", vENDOR_OWNLANDLINE) :
                new ObjectParameter("VENDOR_OWNLANDLINE", typeof(string));
    
            var vENDOR_CONLANDLINEParameter = vENDOR_CONLANDLINE != null ?
                new ObjectParameter("VENDOR_CONLANDLINE", vENDOR_CONLANDLINE) :
                new ObjectParameter("VENDOR_CONLANDLINE", typeof(string));
    
            var vENDOR_USERNAMEParameter = vENDOR_USERNAME != null ?
                new ObjectParameter("VENDOR_USERNAME", vENDOR_USERNAME) :
                new ObjectParameter("VENDOR_USERNAME", typeof(string));
    
            var vENDOR_PASSWORDParameter = vENDOR_PASSWORD != null ?
                new ObjectParameter("VENDOR_PASSWORD", vENDOR_PASSWORD) :
                new ObjectParameter("VENDOR_PASSWORD", typeof(string));
    
            var vENDOR_STATUSParameter = vENDOR_STATUS.HasValue ?
                new ObjectParameter("VENDOR_STATUS", vENDOR_STATUS) :
                new ObjectParameter("VENDOR_STATUS", typeof(int));
    
            var vENDOR_CREATEDBYParameter = vENDOR_CREATEDBY.HasValue ?
                new ObjectParameter("VENDOR_CREATEDBY", vENDOR_CREATEDBY) :
                new ObjectParameter("VENDOR_CREATEDBY", typeof(int));
    
            var vENDOR_CREATEDDATEParameter = vENDOR_CREATEDDATE.HasValue ?
                new ObjectParameter("VENDOR_CREATEDDATE", vENDOR_CREATEDDATE) :
                new ObjectParameter("VENDOR_CREATEDDATE", typeof(System.DateTime));
    
            var vENDOR_MODIFIEDBYParameter = vENDOR_MODIFIEDBY.HasValue ?
                new ObjectParameter("VENDOR_MODIFIEDBY", vENDOR_MODIFIEDBY) :
                new ObjectParameter("VENDOR_MODIFIEDBY", typeof(int));
    
            var vENDOR_MODIFIEDDATEParameter = vENDOR_MODIFIEDDATE.HasValue ?
                new ObjectParameter("VENDOR_MODIFIEDDATE", vENDOR_MODIFIEDDATE) :
                new ObjectParameter("VENDOR_MODIFIEDDATE", typeof(System.DateTime));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vendors_details", vENDOR_IDParameter, vENDOR_ORGANIZATIONNAMEParameter, vENDOR_ORGANIZATIONMOBILEParameter, vENDOR_ORGANIZATIONLANDLINEParameter, vENDOR_OWNFIRSTNAMEParameter, vENDOR_OWNLASTNAMEParameter, vENDOR_CONFIRSTNAMEParameter, vENDOR_CONLASTNAMEParameter, vENDOR_EMAILIDParameter, vENDOR_ADDRESSParameter, vENDOR_OWNMOBILEParameter, vENDOR_CONMOBILEParameter, vENDOR_OWNLANDLINEParameter, vENDOR_CONLANDLINEParameter, vENDOR_USERNAMEParameter, vENDOR_PASSWORDParameter, vENDOR_STATUSParameter, vENDOR_CREATEDBYParameter, vENDOR_CREATEDDATEParameter, vENDOR_MODIFIEDBYParameter, vENDOR_MODIFIEDDATEParameter, operationParameter);
        }
    
        public virtual int city_data(Nullable<int> id, string city_name, string operation)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("city_data", idParameter, city_nameParameter, operationParameter);
        }
    
        public virtual ObjectResult<GetUserDetailsforTrip_Result> GetUserDetailsforTrip(Nullable<int> trip_ID)
        {
            var trip_IDParameter = trip_ID.HasValue ?
                new ObjectParameter("Trip_ID", trip_ID) :
                new ObjectParameter("Trip_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserDetailsforTrip_Result>("GetUserDetailsforTrip", trip_IDParameter);
        }
    
        public virtual int locations_data(Nullable<int> loc_id, string loc_name, Nullable<int> city_id, string operation)
        {
            var loc_idParameter = loc_id.HasValue ?
                new ObjectParameter("loc_id", loc_id) :
                new ObjectParameter("loc_id", typeof(int));
    
            var loc_nameParameter = loc_name != null ?
                new ObjectParameter("loc_name", loc_name) :
                new ObjectParameter("loc_name", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(int));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("locations_data", loc_idParameter, loc_nameParameter, city_idParameter, operationParameter);
        }
    
        public virtual ObjectResult<masterstatus_data_Result> masterstatus_data(Nullable<int> sTATUS_ID, string sATUS_NAME, Nullable<int> sTATUS_CREATEDBY, Nullable<System.DateTime> sTATUS_CREATEDDATE, Nullable<int> sTATUS_MODIFIEDBY, Nullable<System.DateTime> sTATUS_MODIFIEDDATE, string operation)
        {
            var sTATUS_IDParameter = sTATUS_ID.HasValue ?
                new ObjectParameter("STATUS_ID", sTATUS_ID) :
                new ObjectParameter("STATUS_ID", typeof(int));
    
            var sATUS_NAMEParameter = sATUS_NAME != null ?
                new ObjectParameter("SATUS_NAME", sATUS_NAME) :
                new ObjectParameter("SATUS_NAME", typeof(string));
    
            var sTATUS_CREATEDBYParameter = sTATUS_CREATEDBY.HasValue ?
                new ObjectParameter("STATUS_CREATEDBY", sTATUS_CREATEDBY) :
                new ObjectParameter("STATUS_CREATEDBY", typeof(int));
    
            var sTATUS_CREATEDDATEParameter = sTATUS_CREATEDDATE.HasValue ?
                new ObjectParameter("STATUS_CREATEDDATE", sTATUS_CREATEDDATE) :
                new ObjectParameter("STATUS_CREATEDDATE", typeof(System.DateTime));
    
            var sTATUS_MODIFIEDBYParameter = sTATUS_MODIFIEDBY.HasValue ?
                new ObjectParameter("STATUS_MODIFIEDBY", sTATUS_MODIFIEDBY) :
                new ObjectParameter("STATUS_MODIFIEDBY", typeof(int));
    
            var sTATUS_MODIFIEDDATEParameter = sTATUS_MODIFIEDDATE.HasValue ?
                new ObjectParameter("STATUS_MODIFIEDDATE", sTATUS_MODIFIEDDATE) :
                new ObjectParameter("STATUS_MODIFIEDDATE", typeof(System.DateTime));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<masterstatus_data_Result>("masterstatus_data", sTATUS_IDParameter, sATUS_NAMEParameter, sTATUS_CREATEDBYParameter, sTATUS_CREATEDDATEParameter, sTATUS_MODIFIEDBYParameter, sTATUS_MODIFIEDDATEParameter, operationParameter);
        }
    
        public virtual ObjectResult<USP_DRIVERSAPP_Result> USP_DRIVERSAPP(string oPERATION, Nullable<int> dRIVER_ID, Nullable<int> tRIP_ID)
        {
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            var dRIVER_IDParameter = dRIVER_ID.HasValue ?
                new ObjectParameter("DRIVER_ID", dRIVER_ID) :
                new ObjectParameter("DRIVER_ID", typeof(int));
    
            var tRIP_IDParameter = tRIP_ID.HasValue ?
                new ObjectParameter("TRIP_ID", tRIP_ID) :
                new ObjectParameter("TRIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DRIVERSAPP_Result>("USP_DRIVERSAPP", oPERATIONParameter, dRIVER_IDParameter, tRIP_IDParameter);
        }
    
        public virtual ObjectResult<vehicles_data_Result> vehicles_data(Nullable<int> vEHICLE_ID, Nullable<int> vEHICLE_TYPE, Nullable<int> vEHICLE_VENDORID, string operation)
        {
            var vEHICLE_IDParameter = vEHICLE_ID.HasValue ?
                new ObjectParameter("VEHICLE_ID", vEHICLE_ID) :
                new ObjectParameter("VEHICLE_ID", typeof(int));
    
            var vEHICLE_TYPEParameter = vEHICLE_TYPE.HasValue ?
                new ObjectParameter("VEHICLE_TYPE", vEHICLE_TYPE) :
                new ObjectParameter("VEHICLE_TYPE", typeof(int));
    
            var vEHICLE_VENDORIDParameter = vEHICLE_VENDORID.HasValue ?
                new ObjectParameter("VEHICLE_VENDORID", vEHICLE_VENDORID) :
                new ObjectParameter("VEHICLE_VENDORID", typeof(int));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vehicles_data_Result>("vehicles_data", vEHICLE_IDParameter, vEHICLE_TYPEParameter, vEHICLE_VENDORIDParameter, operationParameter);
        }
    
        public virtual int VEHICLES_DETAILS(Nullable<int> vEHICLE_VENDORID, string vEHICLE_NUMBER, Nullable<int> vEHICLE_TYPE, Nullable<int> vEHICLE_SEATS, string vEHICLE_REGISTERNO, string vEHICLE_INSURANCENUMBER, string vEHICLE_POLLUTIONCHECK, Nullable<System.DateTime> vEHICLE_EXPIRYDATE, Nullable<System.DateTime> vEHICLE_INSURANCEEXPIRY, Nullable<System.DateTime> vEHICLE_POLLUTIONEXPIRY, Nullable<System.DateTime> vEHICLE_MAINTANANCEEXPIRY, Nullable<int> vEHICLE_CREATEDBY, Nullable<System.DateTime> vEHICLE_CREATEDDATE, Nullable<int> vEHICLE_MODIFIEDBY, Nullable<System.DateTime> vEHICLE_MODIFIEDDATE, Nullable<int> vEHICLE_STATUS, string oPERATION)
        {
            var vEHICLE_VENDORIDParameter = vEHICLE_VENDORID.HasValue ?
                new ObjectParameter("VEHICLE_VENDORID", vEHICLE_VENDORID) :
                new ObjectParameter("VEHICLE_VENDORID", typeof(int));
    
            var vEHICLE_NUMBERParameter = vEHICLE_NUMBER != null ?
                new ObjectParameter("VEHICLE_NUMBER", vEHICLE_NUMBER) :
                new ObjectParameter("VEHICLE_NUMBER", typeof(string));
    
            var vEHICLE_TYPEParameter = vEHICLE_TYPE.HasValue ?
                new ObjectParameter("VEHICLE_TYPE", vEHICLE_TYPE) :
                new ObjectParameter("VEHICLE_TYPE", typeof(int));
    
            var vEHICLE_SEATSParameter = vEHICLE_SEATS.HasValue ?
                new ObjectParameter("VEHICLE_SEATS", vEHICLE_SEATS) :
                new ObjectParameter("VEHICLE_SEATS", typeof(int));
    
            var vEHICLE_REGISTERNOParameter = vEHICLE_REGISTERNO != null ?
                new ObjectParameter("VEHICLE_REGISTERNO", vEHICLE_REGISTERNO) :
                new ObjectParameter("VEHICLE_REGISTERNO", typeof(string));
    
            var vEHICLE_INSURANCENUMBERParameter = vEHICLE_INSURANCENUMBER != null ?
                new ObjectParameter("VEHICLE_INSURANCENUMBER", vEHICLE_INSURANCENUMBER) :
                new ObjectParameter("VEHICLE_INSURANCENUMBER", typeof(string));
    
            var vEHICLE_POLLUTIONCHECKParameter = vEHICLE_POLLUTIONCHECK != null ?
                new ObjectParameter("VEHICLE_POLLUTIONCHECK", vEHICLE_POLLUTIONCHECK) :
                new ObjectParameter("VEHICLE_POLLUTIONCHECK", typeof(string));
    
            var vEHICLE_EXPIRYDATEParameter = vEHICLE_EXPIRYDATE.HasValue ?
                new ObjectParameter("VEHICLE_EXPIRYDATE", vEHICLE_EXPIRYDATE) :
                new ObjectParameter("VEHICLE_EXPIRYDATE", typeof(System.DateTime));
    
            var vEHICLE_INSURANCEEXPIRYParameter = vEHICLE_INSURANCEEXPIRY.HasValue ?
                new ObjectParameter("VEHICLE_INSURANCEEXPIRY", vEHICLE_INSURANCEEXPIRY) :
                new ObjectParameter("VEHICLE_INSURANCEEXPIRY", typeof(System.DateTime));
    
            var vEHICLE_POLLUTIONEXPIRYParameter = vEHICLE_POLLUTIONEXPIRY.HasValue ?
                new ObjectParameter("VEHICLE_POLLUTIONEXPIRY", vEHICLE_POLLUTIONEXPIRY) :
                new ObjectParameter("VEHICLE_POLLUTIONEXPIRY", typeof(System.DateTime));
    
            var vEHICLE_MAINTANANCEEXPIRYParameter = vEHICLE_MAINTANANCEEXPIRY.HasValue ?
                new ObjectParameter("VEHICLE_MAINTANANCEEXPIRY", vEHICLE_MAINTANANCEEXPIRY) :
                new ObjectParameter("VEHICLE_MAINTANANCEEXPIRY", typeof(System.DateTime));
    
            var vEHICLE_CREATEDBYParameter = vEHICLE_CREATEDBY.HasValue ?
                new ObjectParameter("VEHICLE_CREATEDBY", vEHICLE_CREATEDBY) :
                new ObjectParameter("VEHICLE_CREATEDBY", typeof(int));
    
            var vEHICLE_CREATEDDATEParameter = vEHICLE_CREATEDDATE.HasValue ?
                new ObjectParameter("VEHICLE_CREATEDDATE", vEHICLE_CREATEDDATE) :
                new ObjectParameter("VEHICLE_CREATEDDATE", typeof(System.DateTime));
    
            var vEHICLE_MODIFIEDBYParameter = vEHICLE_MODIFIEDBY.HasValue ?
                new ObjectParameter("VEHICLE_MODIFIEDBY", vEHICLE_MODIFIEDBY) :
                new ObjectParameter("VEHICLE_MODIFIEDBY", typeof(int));
    
            var vEHICLE_MODIFIEDDATEParameter = vEHICLE_MODIFIEDDATE.HasValue ?
                new ObjectParameter("VEHICLE_MODIFIEDDATE", vEHICLE_MODIFIEDDATE) :
                new ObjectParameter("VEHICLE_MODIFIEDDATE", typeof(System.DateTime));
    
            var vEHICLE_STATUSParameter = vEHICLE_STATUS.HasValue ?
                new ObjectParameter("VEHICLE_STATUS", vEHICLE_STATUS) :
                new ObjectParameter("VEHICLE_STATUS", typeof(int));
    
            var oPERATIONParameter = oPERATION != null ?
                new ObjectParameter("OPERATION", oPERATION) :
                new ObjectParameter("OPERATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VEHICLES_DETAILS", vEHICLE_VENDORIDParameter, vEHICLE_NUMBERParameter, vEHICLE_TYPEParameter, vEHICLE_SEATSParameter, vEHICLE_REGISTERNOParameter, vEHICLE_INSURANCENUMBERParameter, vEHICLE_POLLUTIONCHECKParameter, vEHICLE_EXPIRYDATEParameter, vEHICLE_INSURANCEEXPIRYParameter, vEHICLE_POLLUTIONEXPIRYParameter, vEHICLE_MAINTANANCEEXPIRYParameter, vEHICLE_CREATEDBYParameter, vEHICLE_CREATEDDATEParameter, vEHICLE_MODIFIEDBYParameter, vEHICLE_MODIFIEDDATEParameter, vEHICLE_STATUSParameter, oPERATIONParameter);
        }
    
        public virtual ObjectResult<vehicletype_data_Result> vehicletype_data(Nullable<int> vEHICLETYPE_ID, string vEHICLETYPE_NAME, string operation)
        {
            var vEHICLETYPE_IDParameter = vEHICLETYPE_ID.HasValue ?
                new ObjectParameter("VEHICLETYPE_ID", vEHICLETYPE_ID) :
                new ObjectParameter("VEHICLETYPE_ID", typeof(int));
    
            var vEHICLETYPE_NAMEParameter = vEHICLETYPE_NAME != null ?
                new ObjectParameter("VEHICLETYPE_NAME", vEHICLETYPE_NAME) :
                new ObjectParameter("VEHICLETYPE_NAME", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vehicletype_data_Result>("vehicletype_data", vEHICLETYPE_IDParameter, vEHICLETYPE_NAMEParameter, operationParameter);
        }
    }
}
