//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITy()
        {
            this.LOCATIONS = new HashSet<LOCATION>();
        }
    
        public int CITY_ID { get; set; }
        public Nullable<int> CITY_STATEID { get; set; }
        public string CITY_NAME { get; set; }
        public Nullable<int> CITY_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CITY_CREATEDDATE { get; set; }
        public Nullable<int> CITY_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CITY_MODIFIEDDATE { get; set; }
        public Nullable<int> CITY_STATUS { get; set; }
    
        public virtual STATE STATE { get; set; }
        public virtual MASTERSTATU MASTERSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
    }
}
