//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUPONENTIYPURPOSE
    {
        public int COUPON_ID { get; set; }
        public string COUPON_NAME { get; set; }
        public Nullable<int> COUPON_MONEY { get; set; }
        public Nullable<int> COUPON_TYPE { get; set; }
        public string VALIDITY { get; set; }
    }
}
