//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUPONTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUPONTYPE()
        {
            this.COUPONS = new HashSet<COUPON>();
            this.USERCOUPONS = new HashSet<USERCOUPON>();
        }
    
        public int COUPONTYPE_ID { get; set; }
        public string COUPONTYPE_NAME { get; set; }
        public Nullable<int> COUPONTYPE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> COUPONTYPE_CREATEDDATE { get; set; }
        public Nullable<int> COUPONTYPE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> COUPON_MODIFIEDDATE { get; set; }
        public Nullable<int> COUPONTYPE_STATUS { get; set; }
        public Nullable<bool> COUPONTYPE_ONETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUPON> COUPONS { get; set; }
        public virtual MASTERSTATU MASTERSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERCOUPON> USERCOUPONS { get; set; }
    }
}
