//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVERTRIPSENTITY
    {
        public int trip_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> vd_id { get; set; }
        public string trip_ExpectedstartDate { get; set; }
        public string trip_expectedenddate { get; set; }
        public string trip_from { get; set; }
        public string trip_to { get; set; }
        public string trip_via { get; set; }
        public string vehicle_number { get; set; }
        public string vehicletype_name { get; set; }
        public string driver_name { get; set; }
        public string driver_mobile { get; set; }
        public string driver_emailid { get; set; }
    }
}
