//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LATLONG
    {
        public int LL_ID { get; set; }
        public Nullable<int> LL_ROUTE_ID { get; set; }
        public Nullable<decimal> LL_LAT { get; set; }
        public Nullable<decimal> LL_LONG { get; set; }
        public string LL_NAME { get; set; }
        public Nullable<int> LL_CREATEDBY { get; set; }
        public Nullable<System.DateTime> LL_CREATEDDATE { get; set; }
        public Nullable<int> LL_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LL_MODIFIEDDATE { get; set; }
        public Nullable<int> LATLONG_STATUS { get; set; }
        public Nullable<int> LL_LOCATIONID { get; set; }
    
        public virtual MASTERSTATU MASTERSTATU { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ROUTE ROUTE { get; set; }
    }
}
