//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION()
        {
            this.LATLONGS = new HashSet<LATLONG>();
        }
    
        public int LOCATION_ID { get; set; }
        public Nullable<int> LOCATION_CITYID { get; set; }
        public string LOCATION_NAME { get; set; }
        public Nullable<decimal> LOCATION_LATITUDE { get; set; }
        public Nullable<decimal> LOCATION_LONGITUDE { get; set; }
        public Nullable<int> LOCATION_CREATEDBY { get; set; }
        public Nullable<System.DateTime> LOCATION_CREATEDDATE { get; set; }
        public Nullable<int> LOCATION_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LOCATION_MODIFIEDDATE { get; set; }
        public Nullable<int> LOCATION_STATUS { get; set; }
    
        public virtual CITy CITy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LATLONG> LATLONGS { get; set; }
        public virtual MASTERSTATU MASTERSTATU { get; set; }
    }
}
