//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSENGERSENTITY
    {
        public int USERTRIP_ID { get; set; }
        public Nullable<int> USERTRIP_TRIPID { get; set; }
        public Nullable<int> USERTRIP_PICKUPLOC { get; set; }
        public Nullable<int> USERTRIP_DROPLOC { get; set; }
        public string USERTRIP_VIA { get; set; }
        public Nullable<decimal> USERTRIP_TOTALAMOUNT { get; set; }
        public Nullable<int> USERTRIP_STATUS { get; set; }
        public Nullable<int> USERTRIP_USERID { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_EMAILID { get; set; }
        public string USER_MOBILE { get; set; }
        public Nullable<int> ll_sortorder { get; set; }
        public string fromloc { get; set; }
        public string toloc { get; set; }
        public string actualstarttime { get; set; }
    }
}
