//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATE()
        {
            this.CITIES = new HashSet<CITy>();
        }
    
        public int STATE_ID { get; set; }
        public string STATE_NAME { get; set; }
        public Nullable<int> STATE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> STATE_CREATEDDATE { get; set; }
        public Nullable<int> STATE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> STATE_MODIFIEDDATE { get; set; }
        public Nullable<int> STATE_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITy> CITIES { get; set; }
        public virtual MASTERSTATU MASTERSTATU { get; set; }
    }
}
