//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORT
    {
        public int SUPPORT_ID { get; set; }
        public Nullable<int> SUPPORT_USERID { get; set; }
        public string SUPPORT_SUBJECT { get; set; }
        public string SUPPORT_DESCRIPTION { get; set; }
        public Nullable<int> SUPPORT_CREATEDBY { get; set; }
        public Nullable<System.DateTime> SUPPORT_CREATEDDATE { get; set; }
        public Nullable<int> SUPPORT_MODIFIEDBY { get; set; }
    }
}
