//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temptrip
    {
        public int TEMPTRIP_ID { get; set; }
        public Nullable<int> fromllid { get; set; }
        public Nullable<int> fromtripid { get; set; }
        public string fromlocationname { get; set; }
        public Nullable<int> fromsortorder { get; set; }
        public Nullable<System.DateTime> fromaveragereachtime { get; set; }
        public Nullable<System.DateTime> fromactualreachtime { get; set; }
        public Nullable<int> fromkms { get; set; }
        public Nullable<int> tollid { get; set; }
        public Nullable<int> totripid { get; set; }
        public string tolocationname { get; set; }
        public Nullable<int> tosortorder { get; set; }
        public Nullable<System.DateTime> toaveragereachtime { get; set; }
        public Nullable<System.DateTime> toactualreachtime { get; set; }
        public Nullable<int> tokms { get; set; }
    }
}
