//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONMODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTIONMODE()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int MODE_ID { get; set; }
        public string MODE_NAME { get; set; }
        public Nullable<int> MODE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> MODE_CREATEDDATE { get; set; }
        public Nullable<int> MODE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODE_MODIFIEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
