//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIPLOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIPLOCATION()
        {
            this.USERTRIPS = new HashSet<USERTRIP>();
            this.USERTRIPS1 = new HashSet<USERTRIP>();
        }
    
        public int LL_ID { get; set; }
        public Nullable<int> LL_TRIP_ID { get; set; }
        public Nullable<decimal> LL_LAT { get; set; }
        public Nullable<decimal> LL_LONG { get; set; }
        public string LL_NAME { get; set; }
        public Nullable<int> LL_CREATEDBY { get; set; }
        public Nullable<System.DateTime> LL_CREATEDDATE { get; set; }
        public Nullable<int> LL_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LL_MODIFIEDDATE { get; set; }
        public Nullable<bool> LL_VIA { get; set; }
        public Nullable<int> LL_SORTORDER { get; set; }
        public Nullable<System.DateTime> LL_AVERAGEREACHTIME { get; set; }
        public Nullable<System.DateTime> LL_ACTUALREACHTIME { get; set; }
        public Nullable<int> LL_DIFFPREV { get; set; }
        public Nullable<int> LL_STATUS { get; set; }
        public Nullable<bool> LL_ENDED { get; set; }
        public Nullable<int> LL_KMFROMPICKUP { get; set; }
    
        public virtual TRIPSTATU TRIPSTATU { get; set; }
        public virtual TRIP TRIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTRIP> USERTRIPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTRIP> USERTRIPS1 { get; set; }
    }
}
