//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIPTEMP
    {
        public int TRIPTEMP_ID { get; set; }
        public Nullable<int> trip_id { get; set; }
        public string trip_name { get; set; }
        public Nullable<int> trip_vehicle_id { get; set; }
        public Nullable<int> trip_route_id { get; set; }
        public Nullable<int> fromllid { get; set; }
        public string fromlocationname { get; set; }
        public string fromactualreachtime { get; set; }
        public string fromaveragereachtime { get; set; }
        public Nullable<int> tollid { get; set; }
        public string tolocationname { get; set; }
        public string toaveragereachtime { get; set; }
        public string toactualreachtime { get; set; }
        public string startdate { get; set; }
        public string VIA { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> seat_availableseats { get; set; }
        public Nullable<int> DISTANCE { get; set; }
        public string driver_name { get; set; }
        public string vehicle_number { get; set; }
        public string vehicletype_name { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> fromaveragereachtimenormal { get; set; }
        public Nullable<System.DateTime> fromactualreachtimenormal { get; set; }
        public Nullable<System.DateTime> toaveragereachtimenormal { get; set; }
        public Nullable<System.DateTime> toactualreachtimenormal { get; set; }
    }
}
