//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIPHISTORYENTITY
    {
        public int ID { get; set; }
        public Nullable<int> USERTRIP_ID { get; set; }
        public Nullable<int> PICKUPID { get; set; }
        public string PICKUPNAME { get; set; }
        public Nullable<int> DROPID { get; set; }
        public string DROPNAME { get; set; }
        public string USERTRIP_VIA { get; set; }
        public Nullable<int> USERTRIP_ACTUALDURATION { get; set; }
        public Nullable<int> USERTRIP_DISTANCE { get; set; }
        public Nullable<decimal> USERTRIP_ACTUALAMOUNT { get; set; }
        public Nullable<decimal> USERTRIP_DISCOUNT { get; set; }
        public Nullable<decimal> USERTRIP_TOTALAMOUNT { get; set; }
        public Nullable<int> USERTRIP_STATUS { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public Nullable<int> USER_APPLIEDCOUPON { get; set; }
        public string USER_APPLIEDCOUPONNAME { get; set; }
        public string TRIP_NAME { get; set; }
        public string USERTRIP_PICKUPAVERAGETIME { get; set; }
        public string USERTRIP_PICKUPACTUALTIME { get; set; }
        public string USERTRIP_DROPAVERAGETIME { get; set; }
        public string USERTRIP_DROPACTUALTIME { get; set; }
        public string STARTDATE { get; set; }
        public string VEHICLENUMBER { get; set; }
        public string DRIVERMOBILE { get; set; }
        public string DRIVERNAME { get; set; }
        public string DRIVERIMAGE { get; set; }
        public string STATUS_NAME { get; set; }
    }
}
