//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_REGISTERTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_REGISTERTYPE()
        {
            this.CH_USER = new HashSet<CH_USER>();
        }
    
        public int REGTYPE_ID { get; set; }
        public string REGTYPE_NAME { get; set; }
        public Nullable<int> REGTYPE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> REGTYPE_CREATEDDATE { get; set; }
        public Nullable<int> REGTYPE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> REGTYPE_MODIFIEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CH_USER> CH_USER { get; set; }
    }
}
