//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERCOUPON
    {
        public int COUPON_ID { get; set; }
        public Nullable<int> COUPON_USERID { get; set; }
        public string COUPON_NAME { get; set; }
        public Nullable<int> COUPON_MONEY { get; set; }
        public Nullable<int> COUPON_TYPE { get; set; }
        public Nullable<int> COUPON_CREATEDBY { get; set; }
        public Nullable<System.DateTime> COUPON_CREATEDDATE { get; set; }
        public Nullable<int> COUPON_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> COUPON_MODIFIEDDATE { get; set; }
        public Nullable<int> COUPON_STATUS { get; set; }
    
        public virtual COUPONTYPE COUPONTYPE { get; set; }
        public virtual CH_USER CH_USER { get; set; }
        public virtual MASTERSTATU MASTERSTATU { get; set; }
    }
}
