//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLEDRIVER
    {
        public int VD_ID { get; set; }
        public Nullable<int> VD_VEHICLE_ID { get; set; }
        public Nullable<int> VD_DRIVER_ID { get; set; }
        public Nullable<int> VD_CREATEDBY { get; set; }
        public Nullable<System.DateTime> VD_CREATEDDATE { get; set; }
        public Nullable<int> VD_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> VD_MODIFIEDDATE { get; set; }
    
        public virtual DRIVER DRIVER { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
