//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLETYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICLETYPE()
        {
            this.VEHICLES = new HashSet<VEHICLE>();
        }
    
        public int VEHICLETYPE_ID { get; set; }
        public string VEHICLETYPE_NAME { get; set; }
        public Nullable<int> VEHICLE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> VEHICLE_CREATEDDATE { get; set; }
        public Nullable<int> VEHICLE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> VEHICLE_MODIFIEDDATE { get; set; }
        public Nullable<int> VEHICLETYPE_NOOFSEATS { get; set; }
        public Nullable<decimal> VEHICLETYPE_COSTPERKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLES { get; set; }
    }
}
