//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICLE()
        {
            this.TRIPS = new HashSet<TRIP>();
        }
    
        public int VEHICLE_ID { get; set; }
        public Nullable<int> VEHICLE_VENDORID { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public Nullable<int> VEHICLE_TYPE { get; set; }
        public Nullable<int> VEHICLE_SEATS { get; set; }
        public string VEHICLE_REGISTERNO { get; set; }
        public string VEHICLE_INSURANCENUMBER { get; set; }
        public string VEHICLE_POLLUTIONCHECK { get; set; }
        public Nullable<System.DateTime> VEHICLE_EXPIRYDATE { get; set; }
        public Nullable<System.DateTime> VEHICLE_INSURANCEEXPIRY { get; set; }
        public Nullable<System.DateTime> VEHICLE_POLLUTIONEXPIRY { get; set; }
        public Nullable<System.DateTime> VEHICLE_MAINTANANCEEXPIRY { get; set; }
        public Nullable<int> VEHICLE_CREATEDBY { get; set; }
        public Nullable<System.DateTime> VEHICLE_CREATEDDATE { get; set; }
        public Nullable<int> VEHICLE_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> VEHICLE_MODIFIEDDATE { get; set; }
        public Nullable<int> VEHICLE_STATUS { get; set; }
    
        public virtual MASTERSTATU MASTERSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP> TRIPS { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual VEHICLETYPE VEHICLETYPE { get; set; }
    }
}
