//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WALLET()
        {
            this.WALLETTRANSACTIONS = new HashSet<WALLETTRANSACTION>();
        }
    
        public int WALLET_ID { get; set; }
        public Nullable<int> WALLET_USERID { get; set; }
        public Nullable<decimal> WALLET_AVAILABLEMONEY { get; set; }
        public Nullable<int> WALLET_CREATEDBY { get; set; }
        public Nullable<System.DateTime> WALLET_CREATEDDATE { get; set; }
        public Nullable<int> WALLET_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> WALLET_MODIFIEDDATE { get; set; }
        public Nullable<int> WALLET_STATUS { get; set; }
    
        public virtual MASTERSTATU MASTERSTATU { get; set; }
        public virtual CH_USER CH_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WALLETTRANSACTION> WALLETTRANSACTIONS { get; set; }
    }
}
